#!/usr/bin/env python3
"""
Analysis of receptionist's conversation history loading based on trace 1f064b62-61bc-6f2d-9273-668c50712976
"""

print("="*80)
print("TRACE ANALYSIS: Receptionist Conversation History Loading")
print("Trace ID: 1f064b62-61bc-6f2d-9273-668c50712976")
print("="*80)

print("\n📋 WHAT THE RECEPTIONIST SHOULD BE DOING:")
print("-" * 60)
print("1. Load contact details from GHL")
print("2. Extract custom fields (score, business type, budget, etc.)")
print("3. Load conversation history:")
print("   a. Call get_conversations(contact_id) to get conversation list")
print("   b. Call get_conversation_messages(conv_id) to get messages")
print("   c. Convert GHL messages to LangChain format")
print("   d. Filter out system messages")
print("4. Combine history + current message")
print("5. Pass complete context to supervisor")

print("\n🔍 KEY QUESTIONS TO ANSWER FROM TRACE:")
print("-" * 60)
print("1. Is get_conversations being called?")
print("2. How many conversations are returned?")
print("3. Is get_conversation_messages being called?")
print("4. How many messages are being loaded?")
print("5. Are messages being converted to LangChain format?")
print("6. Are system messages (like 'Opportunity created') being filtered?")
print("7. Is the agent seeing the full conversation context?")

print("\n🐛 POTENTIAL ISSUES TO CHECK:")
print("-" * 60)
print("1. API calls failing silently")
print("2. Empty conversation list")
print("3. Message conversion errors")
print("4. State not being passed correctly")
print("5. Messages being overwritten instead of appended")

print("\n📊 EXPECTED BEHAVIOR:")
print("-" * 60)
print("Based on receptionist_simple_debug.py (lines 53-119):")
print("")
print("1. Lines 58-60: Call get_conversations and log the result")
print("2. Lines 62-65: Check if conversations exist and get first conv ID")
print("3. Lines 67-69: Call get_conversation_messages with conv_id")
print("4. Lines 71-73: Take last 50 messages if more exist")
print("5. Lines 75-109: Convert each message to HumanMessage or AIMessage")
print("6. Lines 145-146: Combine history + current messages")

print("\n✅ WHAT TO LOOK FOR IN TRACE:")
print("-" * 60)
print("1. Log entries starting with '[DEBUG]' from receptionist")
print("2. 'get_conversations returned: type=..., length=...'")
print("3. 'get_conversation_messages returned: type=..., length=...'")
print("4. 'Processing X messages for conversion'")
print("5. 'Total messages after combination: X'")

print("\n❌ RED FLAGS:")
print("-" * 60)
print("1. 'No conversations found' - means history not loading")
print("2. 'conv_messages is not a list' - API format issue")
print("3. Low message count when should be higher")
print("4. Missing [DEBUG] entries - code not executing")

print("\n💡 SYSTEM MESSAGE FILTERING:")
print("-" * 60)
print("The current implementation does NOT filter system messages.")
print("All messages with 'body' content are included, which means:")
print("- 'Opportunity created' messages are included")
print("- 'Contact reply' messages are included")
print("- Any automated GHL messages are included")
print("")
print("This could be causing agents to see irrelevant system messages.")

print("\n🔧 RECOMMENDATIONS:")
print("-" * 60)
print("1. Add filtering for system messages in message conversion loop")
print("2. Check for specific message types to exclude")
print("3. Add more detailed logging for each message processed")
print("4. Verify the contact_id is being passed correctly")
print("5. Check if conversation history is being loaded at all")

print("\n📝 NEXT STEPS:")
print("-" * 60)
print("1. Check the actual trace logs for [DEBUG] entries")
print("2. Look for the specific get_conversations and get_conversation_messages calls")
print("3. Count how many messages are being processed")
print("4. Verify the final message count passed to supervisor")
print("5. Check if system messages are polluting the conversation context")