# Google Cloud Build configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ghl-langgraph-agent:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ghl-langgraph-agent:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ghl-langgraph-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ghl-langgraph-agent:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '100'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ghl-langgraph-agent:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY