[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn src.api.webhook:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10