services:
  # Main web service for webhook endpoint
  - type: web
    name: ghl-langgraph-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: GHL_API_TOKEN
        sync: false
      - key: GHL_LOCATION_ID
        sync: false
      - key: GHL_CALENDAR_ID
        sync: false
      - key: GHL_ASSIGNED_USER_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
    
  # Background worker for processing queue
  - type: worker
    name: ghl-message-processor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - fromGroup: shared-env